# Generated by Django 5.2.5 on 2025-08-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount_percent',
            field=models.FloatField(default=0.0),
        ),
    ]
